application:
  subdomain: moltis
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://moltis:13131/
services:
  moltis:
    # ghcr.io/moltis-org/moltis:20260417.01
    # upstream: ghcr.io/moltis-org/moltis:20260902.03
    image: registry.lazycat.cloud/czyt/moltis-org/moltis:0aae21b5483e47ab
    environment:
      - MOLTIS_NO_TLS=true
      - MOLTIS_BEHIND_PROXY=true
      - MOLTIS_CONFIG_DIR=/home/moltis/.config/moltis
      - MOLTIS_DATA_DIR=/home/moltis/.moltis
      - MOLTIS_BIND=0.0.0.0
      - MOLTIS_WEBAUTHN_RP_ID=${LAZYCAT_APP_DOMAIN}
      - MOLTIS_WEBAUTHN_ORIGIN=https://${LAZYCAT_APP_DOMAIN}
      - MOLTIS_TOOLS__EXEC__SANDBOX__IMAGE=registry.lazycat.cloud/czyt/library/ubuntu:8f90a5a3ae20b77f
      - MOLTIS_TOOLS__BROWSER__SANDBOX_IMAGE=registry.lazycat.cloud/czyt/browserless/chromium:f62e87b57509333c
    binds:
      - /lzcapp/var/config:/home/moltis/.config/moltis
      - /lzcapp/var/data:/home/moltis/.moltis
    setup_script: |
      mkdir -p /home/moltis/.config/moltis
      mkdir -p /home/moltis/.moltis
      chown -R moltis:moltis /home/moltis
